#!/usr/bin/env python3
"""Mine DINO object_queries from US ontology corpus + eval_seed.

Writes ontology/tools/vision_queries_mined.yaml and refreshes
src/zataone/policy_engine/corpus/vision_queries.py

Run: python ontology/tools/build_vision_queries.py
"""
from __future__ import annotations

import glob
import re
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "corpus"

# Visual nouns/phrases from ontology detection + eval (compliance-relevant, not generic tokens).
_CATEGORY_HINTS: dict[str, list[str]] = {
    "misleading": ["money", "cash", "banknote", "before after", "fake button"],
    "health": ["pill", "medicine", "syringe", "supplement", "before after"],
    "financial": ["money", "cash", "banknote", "cryptocurrency", "credit card"],
    "gambling": ["casino", "dice", "poker chips", "roulette", "slot machine", "betting"],
    "drugs": ["cigarette", "cigar", "vape", "tobacco", "nicotine", "e-cigarette"],
    "alcohol": ["beer", "wine", "alcohol", "liquor", "cocktail"],
    "ip_trademark": ["counterfeit", "fake logo", "replica handbag", "luxury handbag"],
    "minors": ["child", "teenager", "young model"],
    "political": ["campaign poster", "election badge"],
    "weapons": ["weapon", "gun", "knife", "ammunition", "explosive"],
}

_STOP = frozenset(
    "advertising advertisers including without required products services content".split()
)


def _mine_tokens(text: str) -> list[str]:
    return [
        w
        for w in re.findall(r"[a-z][a-z0-9'-]{3,}", text.lower())
        if w not in _STOP
    ]


def mine_category_queries() -> dict[str, list[str]]:
    by_cat: dict[str, Counter] = defaultdict(Counter)
    for path in sorted(CORPUS.glob("*_us.yaml")):
        doc = yaml.safe_load(path.open(encoding="utf-8")) or {}
        for cl in doc.get("clauses") or []:
            cat = str(cl.get("category_id") or "")
            if "image" not in (cl.get("modalities") or []) and "video" not in (
                cl.get("modalities") or []
            ):
                continue
            for t in _mine_tokens(str(cl.get("text") or "")):
                by_cat[cat][t] += 1
        for r in doc.get("rules") or []:
            cat = str(r.get("category_id") or "")
            if "image" not in (r.get("modalities") or []) and "video" not in (
                r.get("modalities") or []
            ):
                continue
            for t in _mine_tokens(str(r.get("detection") or "")):
                by_cat[cat][t] += 1

    out: dict[str, list[str]] = {}
    for cat, hints in _CATEGORY_HINTS.items():
        mined = [w for w, _ in by_cat.get(cat, Counter()).most_common(8)]
        merged: list[str] = []
        seen: set[str] = set()
        for q in hints + mined:
            q = q.strip().lower()
            if not q or q in seen:
                continue
            seen.add(q)
            merged.append(q)
        out[cat] = merged[:12]
    out["weapons"] = list(_CATEGORY_HINTS["weapons"])
    return out


def main() -> int:
    cat_queries = mine_category_queries()
    flat: list[str] = []
    seen: set[str] = set()
    for labels in cat_queries.values():
        for q in labels:
            if q not in seen:
                seen.add(q)
                flat.append(q)

    mined_path = ROOT / "tools" / "vision_queries_mined.yaml"
    mined_path.write_text(
        yaml.dump(
            {"category_vision_queries": cat_queries, "object_queries": flat},
            sort_keys=False,
            allow_unicode=True,
        ),
        encoding="utf-8",
    )

    py_path = (
        Path(__file__).resolve().parents[2]
        / "src/zataone/policy_engine/corpus/vision_queries.py"
    )
    lines = [
        '# zataone — corpus-mined Grounding DINO queries (generated by build_vision_queries.py)\n',
        "from __future__ import annotations\n",
        "CATEGORY_VISION_QUERIES: dict[str, list[str]] = "
        + repr(cat_queries)
        + "\n",
        "OBJECT_QUERIES: list[str] = " + repr(flat) + "\n",
        "\n\ndef vision_labels_for_category(category_id: str) -> list[str]:\n",
        "    return list(CATEGORY_VISION_QUERIES.get(category_id, []))\n",
    ]
    py_path.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {mined_path} ({len(flat)} object queries)")
    print(f"Updated {py_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
