#!/usr/bin/env python3
"""Measure what a pack's hits are actually worth, per matcher, on the dev split.

The matcher ships three fixed confidences — 0.92 for a phrase, 0.88 for a regex, 0.72 for
a term — applied identically to all 54 packs. They were never measured, and the benchmark
says they cannot all be right: category recall ranges from 0.80 down to 0.00, so a term
hit on the health pack and a term hit on the political pack are plainly not equally
informative.

This computes, per (pack, matcher), the share of hits that landed on a row whose gold
label is non_compliant *and* whose gold categories include the pack's category. Firing on
a non-compliant row for the wrong reason is not a win, so the category has to agree.

Counts are small and long-tailed, so the estimate is shrunk toward the matcher's shipped
prior: conf = (correct + m*prior) / (hits + m). A pack with three hits stays near the
prior; a pack with sixty moves to what it earned.

Reads the dev split only. Test stays untouched, and train is what the packs were mined
from, so neither can price them honestly.

Writes:
  ontology/patterns/confidence.yaml

Usage:
  python ontology/tools/calibrate_pack_confidence.py
  python ontology/tools/calibrate_pack_confidence.py --split dev --min-hits 5
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ONTOLOGY = Path(__file__).resolve().parent.parent
REPO = ONTOLOGY.parent
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(ONTOLOGY))

OUT = ONTOLOGY / "patterns" / "confidence.yaml"

# Shipped constants, used as the shrinkage prior.
PRIORS = {"phrase": 0.92, "regex": 0.88, "term": 0.72}

# Pseudo-count weight. 8 means a pack needs roughly that many hits before the measurement
# outweighs the prior.
SHRINKAGE = 8.0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--split", default="dev", help="eval split to calibrate on (default: dev)")
    ap.add_argument("--min-hits", type=int, default=3, help="skip cells with fewer hits")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if args.split == "test":
        print("refusing to calibrate on test — that is the holdout", file=sys.stderr)
        return 2

    os.environ["ZATAONE_EVAL_INCLUDE_HARVESTED"] = "1"
    os.environ["ZATAONE_EVAL_SPLITS"] = args.split

    from examples.load_eval import load_eval_examples
    from zataone.policy_engine.hybrid.lexical import match_lexical
    from zataone.policy_engine.hybrid.pack_loader import load_pattern_packs

    rows = load_eval_examples(str(ONTOLOGY))
    packs = load_pattern_packs(approved_only=True)
    if not rows or not packs:
        print("no eval rows or no packs", file=sys.stderr)
        return 1

    # (canonical_id, matcher) -> [hits, correct]
    tally: dict[tuple[str, str], list[int]] = defaultdict(lambda: [0, 0])

    for row in rows:
        content = (row.get("content") or "").strip()
        if not content:
            continue
        label = row.get("label")
        gold_cats = set(row.get("category_ids") or [])
        for cid, pack in packs.items():
            hits = match_lexical(content, pack)
            if not hits:
                continue
            correct = label == "non_compliant" and pack.category_id in gold_cats
            seen: set[str] = set()
            for h in hits:
                if h.matcher in seen:
                    continue
                seen.add(h.matcher)
                cell = tally[(cid, h.matcher)]
                cell[0] += 1
                cell[1] += int(correct)

    table: dict[str, dict[str, float]] = defaultdict(dict)
    report: list[tuple[str, str, int, int, float, float]] = []
    for (cid, matcher), (hits, correct) in sorted(tally.items()):
        prior = PRIORS.get(matcher, 0.75)
        if hits < args.min_hits:
            continue
        conf = (correct + SHRINKAGE * prior) / (hits + SHRINKAGE)
        conf = round(min(0.99, max(0.05, conf)), 3)
        table[cid][matcher] = conf
        report.append((cid, matcher, hits, correct, correct / hits, conf))

    doc = {
        "schema_version": 1,
        "calibrated_on": {"split": args.split, "rows": len(rows)},
        "method": (
            "share of hits landing on a non_compliant row whose gold categories include "
            "the pack's category, shrunk toward the shipped constant with "
            f"{SHRINKAGE:g} pseudo-counts"
        ),
        "priors": PRIORS,
        "min_hits": args.min_hits,
        "packs": {k: dict(sorted(v.items())) for k, v in sorted(table.items())},
    }

    if not args.dry_run:
        with OUT.open("w", encoding="utf-8", newline="") as f:
            f.write("# Generated by ontology/tools/calibrate_pack_confidence.py — do not hand-edit.\n")
            yaml.safe_dump(doc, f, sort_keys=False, allow_unicode=True, width=100)

    report.sort(key=lambda r: r[5])
    print(f"rows={len(rows)} split={args.split} packs={len(packs)} cells={len(report)}")
    print(f"\n{'pack':52} {'matcher':8} {'hits':>5} {'ok':>4} {'raw':>6} {'conf':>6}")
    for cid, matcher, hits, correct, raw, conf in report:
        print(f"{cid:52} {matcher:8} {hits:5d} {correct:4d} {raw:6.2f} {conf:6.3f}")
    if not args.dry_run:
        print(f"\nwrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
