#!/usr/bin/env python3
"""Coverage and label-hazard report for the labelled eval corpus.

Answers, from the YAML alone (no models): how much of the corpus is expert-labelled,
which categories are too thin to measure, how many rows are descriptions rather than
real creatives, how the compliant minimal pairs were made, and how wide the error
bars on recall are for each split. Writes Markdown so the numbers can be diffed as
the corpus changes.

  python3.11 ontology/tools/data_quality_report.py
  python3.11 ontology/tools/data_quality_report.py --out ontology/examples/DATA_QUALITY.md
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ONTOLOGY = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ONTOLOGY))

from examples.load_eval import load_eval_with_sources  # noqa: E402

OUT = ONTOLOGY / "examples" / "DATA_QUALITY.md"

# Rows per category and label below which a per-category rate is mostly noise
# (100 positives puts a 90% recall at roughly +/-6 points).
MIN_PER_CELL = 100
_FRAGMENT_CHARS = 30
_TECHNIQUE_RE = re.compile(r"technique:\s*([a-z_]+)")


def recall_half_width(positives: int, recall: float = 0.9) -> float | None:
    """95% normal-approximation half-width, in points, for a recall near ``recall``."""
    if positives <= 0:
        return None
    return round(196 * math.sqrt(recall * (1 - recall) / positives), 1)


def table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(" --- " for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def build_report(examples: list[dict], sources: dict[str, str]) -> str:
    labels = ("non_compliant", "compliant", "borderline")
    total = len(examples)
    parts = [
        "# Eval data quality",
        "",
        "Generated by `ontology/tools/data_quality_report.py`; do not hand-edit.",
        "",
        f"**{total} labelled rows.**",
        "",
    ]

    by_who = Counter((e.get("labeled_by") or "?", e.get("label")) for e in examples)
    who_rows = []
    for who in sorted({w for w, _ in by_who}):
        n = sum(by_who[(who, lab)] for lab in labels)
        who_rows.append([who, *(by_who[(who, lab)] for lab in labels), n, f"{100 * n / total:.0f}%"])
    parts += ["## Who labelled it", "", table(["labeled_by", *labels, "total", "share"], who_rows), ""]

    by_file = Counter(sources.get(e["id"], "?") for e in examples)
    parts += ["## Source files", "", table(["file", "rows"], sorted(by_file.items())), ""]

    split_rows = []
    for split in ("train", "dev", "test"):
        rows = [e for e in examples if str(e.get("split") or "test").lower() == split]
        pos = sum(e.get("label") == "non_compliant" for e in rows)
        expert_pos = sum(
            e.get("label") == "non_compliant" and e.get("labeled_by") == "expert" for e in rows
        )
        split_rows.append(
            [
                split,
                len(rows),
                pos,
                expert_pos,
                recall_half_width(pos) or "–",
                recall_half_width(expert_pos) or "–",
            ]
        )
    parts += [
        "## Splits and error bars",
        "",
        "Splits are grouped by source case (`build_eval_splits.py`). The half-width is the "
        "95% interval on a recall near 90%: a difference smaller than it is noise.",
        "",
        table(
            ["split", "rows", "violations", "expert violations", "± recall (all)", "± recall (expert)"],
            split_rows,
        ),
        "",
    ]

    cell = defaultdict(Counter)
    for e in examples:
        for cat in e.get("category_ids") or ["(none)"]:
            cell[cat][e.get("label")] += 1
    cat_rows = []
    for cat, counts in sorted(cell.items(), key=lambda kv: -sum(kv[1].values())):
        thin = [lab for lab in ("non_compliant", "compliant") if counts[lab] < MIN_PER_CELL]
        cat_rows.append(
            [cat, *(counts[lab] for lab in labels), ", ".join(f"{lab} < {MIN_PER_CELL}" for lab in thin) or "ok"]
        )
    parts += [
        "## Category coverage",
        "",
        f"Target: at least {MIN_PER_CELL} violations and {MIN_PER_CELL} compliant rows per category.",
        "",
        table(["category", *labels, "gap"], cat_rows),
        "",
    ]

    modality = Counter(e.get("modality") or "?" for e in examples)
    described = Counter(
        e.get("modality") or "?" for e in examples if str(e.get("content") or "").lstrip().startswith("[")
    )
    parts += [
        "## Modality",
        "",
        "`described` rows are bracketed descriptions of a creative (\"[Ad showing ...]\"), "
        "not the creative itself; they test the text path only.",
        "",
        table(["modality", "rows", "described"], [[m, n, described[m]] for m, n in modality.most_common()]),
        "",
    ]

    juris = Counter(e.get("jurisdiction") or "?" for e in examples)
    platforms = Counter(e.get("platform") or "(none)" for e in examples)
    parts += [
        "## Jurisdiction and platform",
        "",
        table(["jurisdiction", "rows"], juris.most_common()),
        "",
        table(["platform", "rows"], platforms.most_common()),
        "",
    ]

    techniques = Counter()
    for e in examples:
        if e.get("label") == "compliant":
            m = _TECHNIQUE_RE.search(str(e.get("note") or ""))
            if m:
                techniques[m.group(1)] += 1
    pair_total = sum(techniques.values())
    parts += [
        "## How the compliant minimal pairs were made",
        "",
        "`qualification_added` pairs differ from the violation only by a hedge (\"for many "
        "users\"). A large share teaches a model that a qualifier makes a claim safe.",
        "",
        table(
            ["technique", "rows", "share"],
            [[t, n, f"{100 * n / pair_total:.0f}%"] for t, n in techniques.most_common()],
        ),
        "",
    ]

    fragments = [
        e
        for e in examples
        if e.get("label") == "non_compliant" and len(str(e.get("content") or "").strip()) < _FRAGMENT_CHARS
    ]
    frag_who = Counter(e.get("labeled_by") for e in fragments)
    parts += [
        "## Label hazards",
        "",
        f"- **{len(fragments)} violations under {_FRAGMENT_CHARS} characters** "
        f"({', '.join(f'{w}: {n}' for w, n in frag_who.most_common())}). Many are phrases cut "
        "from a case that was about something else; audit before trusting.",
        f"- **{sum(e.get('label') == 'borderline' for e in examples)} borderline rows** are "
        "excluded from every metric. They are where models hedge; resolving them is high value.",
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    examples, sources = load_eval_with_sources(str(ONTOLOGY))
    report = build_report(examples, sources)
    args.out.write_text(report + "\n", encoding="utf-8")
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
